import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"


const monserrat = Montserrat({
  variable:"--font-monserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Sistem Klinik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monserrat.variable} antialiased flex`}
      >
        <main className="w-full">
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
